name: Validate Ledger

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install hledger
      run: docker pull dastapov/hledger

    - name: Test hledger file
      run: docker run --rm -v $(pwd):/data dastapov/hledger hledger -f /data/hledger.journal check-dates
